version: '3.9'
networks:
  flps-portfolio:
    name: flps-portfolio
services:
  node-server:
    image: felipeflohr/portfolio:1.0
    container_name: portfolio
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:3000"
    networks:
      - flps-portfolio